version: '2.4'
services:
  picassoadmin: 
    build: 
      context: .
      args:
        - VUE_APP_SECURE=$VUE_APP_SECURE
        - VUE_APP_BASE_API=$VUE_APP_BASE_API
        - VUE_APP_BASE_API_PORT=$VUE_APP_BASE_API_PORT
        - VUE_APP_SECRET_CLIENT_GOOGLE=$VUE_APP_SECRET_CLIENT_GOOGLE
        - VUE_APP_ERROR_ENVIRONMENT=$VUE_APP_ERROR_ENVIRONMENT
        - VUE_APP_SENTRY_DSN=$VUE_APP_SENTRY_DSN
        - VUE_APP_TABLEU_API=$VUE_APP_TABLEU_API
        - VUE_APP_TABLEU_TOKEN_API=$VUE_APP_TABLEU_TOKEN_API
        - VUE_APP_TABLEU_TYPE_HR=$VUE_APP_TABLEU_TYPE_HR
        - VUE_APP_TABLEU_TYPE_KOOR=$VUE_APP_TABLEU_TYPE_KOOR
        - VUE_APP_TABLEU_TYPE_STRUKTURAL=$VUE_APP_TABLEU_TYPE_STRUKTURAL
    #ports: 
    #  - "8080:8080"
    mem_limit: 512m
    mem_reservation: 128m
    cpus: 1
    networks: 
      - gateway
    environment: 
      COMPOSE_PROJECT_NAME: picasso-admin-staging
    env_file: 
      - .env

    

networks: 
  gateway:
    external: true
